exports.seed = function (knex) {
  return knex("skills")
    .del()
    .then(function () {
      return knex("skills").insert([
        { name: "JavaScript", level: 1 },
        {
          name: "JavaScript",
          level: 2,
        },
        { name: "JavaScript", level: 3 },
        {
          name: "React",
          level: 1,
        },
        { name: "React", level: 2 },
        { name: "React", level: 3 },
        { name: "Node.js", level: 1 },
        { name: "Node.js", level: 2 },
        { name: "Node.js", level: 3 },
        { name: "Express.js", level: 1 },
        { name: "Express.js", level: 2 },
        { name: "Express.js", level: 3 },
        { name: "MongoDB", level: 1 },
        { name: "MongoDB", level: 2 },
        { name: "MongoDB", level: 3 },
        { name: "PostgreSQL", level: 1 },
        { name: "PostgreSQL", level: 2 },
        { name: "PostgreSQL", level: 3 },
        { name: "HTML", level: 1 },
        { name: "HTML", level: 2 },
        { name: "HTML", level: 3 },
        { name: "CSS", level: 1 },
        { name: "CSS", level: 2 },
        { name: "CSS", level: 3 },
        { name: "SASS", level: 1 },
        { name: "SASS", level: 2 },
        { name: "SASS", level: 3 },
        { name: "Git", level: 1 },
        { name: "Git", level: 2 },
        { name: "Git", level: 3 },
        { name: "GitHub", level: 1 },
        { name: "GitHub", level: 2 },
        { name: "GitHub", level: 3 },
        { name: "Heroku", level: 1 },
        { name: "Heroku", level: 2 },
        { name: "Heroku", level: 3 },
        { name: "Netlify", level: 1 },
        { name: "Netlify", level: 2 },
        { name: "Netlify", level: 3 },
        { name: "Figma", level: 1 },
        { name: "Figma", level: 2 },
        { name: "Figma", level: 3 },
        { name: "Adobe XD", level: 1 },
        { name: "Adobe XD", level: 2 },
        { name: "Adobe XD", level: 3 },
        { name: "Adobe Photoshop", level: 1 },
        { name: "Adobe Photoshop", level: 2 },
        { name: "Adobe Photoshop", level: 3 },
        { name: "Adobe Illustrator", level: 1 },
        { name: "Adobe Illustrator", level: 2 },
        { name: "Adobe Illustrator", level: 3 },
        { name: "Adobe InDesign", level: 1 },
        { name: "Adobe InDesign", level: 2 },
        { name: "Adobe InDesign", level: 3 },
        { name: "Adobe Premiere Pro", level: 1 },
        { name: "Adobe Premiere Pro", level: 2 },
        { name: "Adobe Premiere Pro", level: 3 },
        { name: "Adobe After Effects", level: 1 },
        { name: "Adobe After Effects", level: 2 },
        { name: "Adobe After Effects", level: 3 },
        { name: "Adobe Lightroom", level: 1 },
        { name: "Adobe Lightroom", level: 2 },
        { name: "Adobe Lightroom", level: 3 },
        { name: "C++", level: 1 },
        { name: "C++", level: 2 },
        { name: "C++", level: 3 },
        { name: "C#", level: 1 },
        { name: "C#", level: 2 },
        { name: "C#", level: 3 },
        { name: "Java", level: 1 },
        { name: "Java", level: 2 },
        { name: "Java", level: 3 },
        { name: "Python", level: 1 },
        { name: "Python", level: 2 },
        { name: "Python", level: 3 },
        { name: "Ruby", level: 1 },
        { name: "Ruby", level: 2 },
        { name: "Ruby", level: 3 },
        { name: "Swift", level: 1 },
        { name: "Swift", level: 2 },
        { name: "Swift", level: 3 },
        { name: "Kotlin", level: 1 },
        { name: "Kotlin", level: 2 },
        { name: "Kotlin", level: 3 },
        { name: "PHP", level: 1 },
        { name: "PHP", level: 2 },
        { name: "PHP", level: 3 },
        { name: "SQL", level: 1 },
        { name: "SQL", level: 2 },
        { name: "SQL", level: 3 },
        { name: "MySQL", level: 1 },
        { name: "MySQL", level: 2 },
        { name: "MySQL", level: 3 },
        { name: "Firebase", level: 1 },
        { name: "Firebase", level: 2 },
        { name: "Firebase", level: 3 },
        { name: "AWS", level: 1 },
        { name: "AWS", level: 2 },
        { name: "AWS", level: 3 },
        { name: "Docker", level: 1 },
        { name: "Docker", level: 2 },
        { name: "Docker", level: 3 },
        { name: "Linux", level: 1 },
        { name: "Linux", level: 2 },
        { name: "Linux", level: 3 },
        { name: "Windows", level: 1 },
        { name: "Windows", level: 2 },
        { name: "Windows", level: 3 },
        { name: "MacOS", level: 1 },
        { name: "MacOS", level: 2 },
        { name: "MacOS", level: 3 },
        { name: "Android", level: 1 },
        { name: "Android", level: 2 },
        { name: "Android", level: 3 },
        { name: "iOS", level: 1 },
        { name: "iOS", level: 2 },
        { name: "iOS", level: 3 },
        { name: "Windows Phone", level: 1 },
        { name: "Windows Phone", level: 2 },
        { name: "Windows Phone", level: 3 },
        { name: "React Native", level: 1 },
        { name: "React Native", level: 2 },
        { name: "React Native", level: 3 },
        { name: "Flutter", level: 1 },
        { name: "Flutter", level: 2 },
        { name: "Flutter", level: 3 },
      ]);
    });
};
